### ISSUE TITLE
Pg attribute naming

### ISSUE THREAD

**Issue by jrmerz** [UCDavisLibrary/price-the-vintage#23]
This a small thing, but thought I would bring it up to verify...

The id attribute names in pg use _ and the other attribute names just run words together.

Ex:
page_id
mark_id

vs

winetype
caseprice
bottletype

**Comment by qjhart** [comment]
These are mostly reminants from decisions that don't mean much anymore.  I personally prefer the underscore, but defered to some standard camelCasing from nodal (wineType).  In reality, these should all be wine_type_id, but since the primary key is readable, I leave that off, which maybe is a mistake as well. Happy to standardize back to wine_type, case_price, per_price, bottle_type.

**Comment by qjhart** [comment]
Added to https://github.com/UCDavisLibrary/wine-price-api/issues/25
